# Использовать дерево gentoo как основное для поиска зависимостей
masters = gentoo
# Использовать современные форматы Manifest
thin-manifests = true
sign-manifests = false
# Обязательно для новых оверлеев
cache-formats = md5-dict
